# Generated by Django 4.0.1 on 2022-01-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_data',
            field=models.DateTimeField(null=True, verbose_name='Срок виконання'),
        ),
    ]
