# Generated by Django 4.1.4 on 2023-01-13 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_task_options_task_date_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('planned_date', '-created_date'), 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_data',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='performed',
        ),
        migrations.AddField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Час створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='performed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час виконання'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланований час виконання'),
        ),
    ]
