# Generated by Django 4.1.4 on 2023-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_category_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_date',), 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
    ]
